<!doctype html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="theme-color" content="#6f1f2c">
<title>Sales100 | ANC Logistics Solutions</title>
<style>
:root{
  --anc:#721f2d;--anc-2:#8f2d3c;--anc-dark:#3d1620;--gold:#f4c430;--ink:#151922;
  --muted:#6d7280;--line:#e7e8ec;--paper:#ffffff;--bg:#f5f6f8;--green:#1f9d6a;
  --red:#d74b55;--blue:#3667d6;--shadow:0 12px 30px rgba(30,22,25,.08);
  --radius:18px;--sidebar:270px;
}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:"Segoe UI",Tahoma,Arial,sans-serif;background:var(--bg);color:var(--ink);min-height:100vh}
button,input,select{font:inherit}.app{display:grid;grid-template-columns:var(--sidebar) minmax(0,1fr);min-height:100vh}
.sidebar{background:linear-gradient(180deg,#491721 0%,#6f1f2c 58%,#43131d 100%);color:#fff;padding:22px 16px;position:sticky;top:0;height:100vh;display:flex;flex-direction:column;z-index:30;box-shadow:-12px 0 35px rgba(35,10,16,.16)}
.brand{display:flex;align-items:center;gap:12px;padding:7px 8px 24px;border-bottom:1px solid rgba(255,255,255,.13)}
.brand img{width:88px;height:auto;filter:drop-shadow(0 4px 8px rgba(0,0,0,.14));background:#fff;border-radius:11px;padding:6px}
.brand-copy strong{display:block;font-size:21px;letter-spacing:.3px}.brand-copy span{display:block;font-size:11px;color:#e8cfd4;margin-top:4px}
.nav{display:grid;gap:7px;margin-top:24px}.nav button{border:0;background:transparent;color:#efdfe3;text-align:right;padding:13px 14px;border-radius:12px;cursor:pointer;display:flex;align-items:center;gap:12px;transition:.2s}
.nav button:hover{background:rgba(255,255,255,.09);color:#fff}.nav button.active{background:#fff;color:var(--anc);box-shadow:0 8px 20px rgba(0,0,0,.13);font-weight:800}.nav .ico{width:25px;height:25px;border-radius:8px;background:rgba(255,255,255,.12);display:grid;place-items:center;font-size:13px}.nav button.active .ico{background:#f8eef0}
.sidebar-foot{margin-top:auto;padding:16px 10px 4px;color:#dfc7cc;font-size:12px}.online{display:inline-block;width:8px;height:8px;border-radius:50%;background:#65d69d;margin-left:7px;box-shadow:0 0 0 5px rgba(101,214,157,.13)}
.main{min-width:0}.topbar{height:86px;background:rgba(255,255,255,.94);backdrop-filter:blur(10px);border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 28px;position:sticky;top:0;z-index:20}
.title-wrap{display:flex;align-items:center;gap:13px}.menu-btn{display:none;border:0;background:#f4ecee;color:var(--anc);width:42px;height:42px;border-radius:12px;cursor:pointer}.title h1{font-size:24px;margin:0}.title p{margin:4px 0 0;color:var(--muted);font-size:13px}.top-actions{display:flex;align-items:center;gap:10px}.select,.btn{height:42px;border:1px solid var(--line);background:#fff;border-radius:11px;padding:0 13px;color:var(--ink)}.btn{cursor:pointer;font-weight:700}.btn-primary{border-color:var(--anc);background:var(--anc);color:#fff;box-shadow:0 7px 18px rgba(114,31,45,.2)}.btn-primary:hover{background:var(--anc-2)}
.content{padding:24px 28px 38px;max-width:1660px;margin:auto}.hero{background:linear-gradient(120deg,#5f1b28,#812a3a);color:#fff;border-radius:22px;padding:23px 25px;display:flex;justify-content:space-between;align-items:center;position:relative;overflow:hidden;box-shadow:var(--shadow);margin-bottom:19px}.hero:before,.hero:after{content:"";position:absolute;border:1px solid rgba(244,196,48,.22);border-radius:50%}.hero:before{width:260px;height:260px;left:-85px;top:-115px}.hero:after{width:150px;height:150px;left:56px;bottom:-100px}.hero h2{margin:0 0 7px;font-size:22px}.hero p{margin:0;color:#efd9dd;font-size:13px}.hero-badge{background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.18);padding:10px 14px;border-radius:13px;font-weight:800;white-space:nowrap}.hero-badge b{color:var(--gold)}
.kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:15px;margin-bottom:17px}.card{background:var(--paper);border:1px solid var(--line);border-radius:var(--radius);box-shadow:0 8px 24px rgba(31,27,29,.045)}.kpi{padding:18px;position:relative;overflow:hidden}.kpi:after{content:"";position:absolute;right:0;top:0;width:4px;height:100%;background:var(--anc)}.kpi-head{display:flex;align-items:center;justify-content:space-between;color:var(--muted);font-size:13px}.kpi-icon{width:38px;height:38px;border-radius:11px;background:#f8edef;color:var(--anc);display:grid;place-items:center;font-weight:900}.kpi-value{font-size:27px;font-weight:900;margin:10px 0 5px;letter-spacing:-.6px}.trend{font-size:12px;color:var(--muted)}.trend.up{color:var(--green)}.trend.down{color:var(--red)}
.grid-2{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(290px,.8fr);gap:17px;margin-bottom:17px}.panel{padding:19px}.panel-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:17px}.panel-head h3{margin:0;font-size:16px}.panel-head p{margin:5px 0 0;font-size:12px;color:var(--muted)}.pill{font-size:11px;padding:7px 10px;border-radius:999px;background:#f6edef;color:var(--anc);font-weight:800}
.chart{height:255px;display:flex;align-items:flex-end;gap:10px;padding:13px 5px 8px;border-bottom:1px solid var(--line);position:relative;background:linear-gradient(to top,rgba(231,232,236,.55) 1px,transparent 1px);background-size:100% 25%}.bar-wrap{flex:1;height:100%;display:flex;align-items:flex-end;justify-content:center;position:relative}.bar{width:min(35px,72%);background:linear-gradient(180deg,var(--anc-2),var(--anc));border-radius:8px 8px 3px 3px;min-height:9px;transition:.25s;position:relative}.bar:hover{filter:brightness(1.1);transform:translateY(-2px)}.bar span{position:absolute;top:-24px;left:50%;transform:translateX(-50%);font-size:10px;font-weight:800;color:var(--ink)}.chart-labels{display:flex;gap:10px;padding-top:8px}.chart-labels span{flex:1;text-align:center;color:var(--muted);font-size:10px}
.gauge{width:190px;height:190px;border-radius:50%;margin:8px auto 14px;background:conic-gradient(var(--anc) 0 82%,#eee 82% 100%);display:grid;place-items:center}.gauge:before{content:"";width:138px;height:138px;background:#fff;border-radius:50%;position:absolute}.gauge strong,.gauge small{position:relative;z-index:1}.gauge strong{font-size:34px;color:var(--anc)}.gauge small{display:block;color:var(--muted);font-size:11px;text-align:center}.gauge-center{text-align:center;z-index:2}.target-row{display:flex;justify-content:space-between;font-size:12px;color:var(--muted);border-top:1px solid var(--line);padding-top:13px}.target-row b{color:var(--ink)}
.bottom-grid{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(0,.8fr);gap:17px}.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse;min-width:640px}.table th,.table td{padding:12px 10px;border-bottom:1px solid var(--line);text-align:right;font-size:12px}.table th{color:var(--muted);font-weight:700;background:#fafafa}.rank{width:26px;height:26px;border-radius:8px;background:#f4ecee;color:var(--anc);display:grid;place-items:center;font-weight:900}.person{display:flex;align-items:center;gap:9px}.avatar{width:32px;height:32px;border-radius:50%;background:linear-gradient(135deg,#8a2b3b,#531923);color:#fff;display:grid;place-items:center;font-size:11px;font-weight:900}.progress{height:7px;border-radius:999px;background:#eee;overflow:hidden;min-width:90px}.progress i{display:block;height:100%;background:var(--anc);border-radius:inherit}.status{display:inline-block;padding:6px 9px;border-radius:999px;font-size:10px;font-weight:800}.status.good{background:#eaf7f1;color:#18764f}.status.warn{background:#fff6df;color:#986b00}.status.bad{background:#fdebed;color:#b62f3b}
.feed{display:grid;gap:14px}.feed-item{display:grid;grid-template-columns:38px 1fr auto;gap:10px;align-items:start}.feed-ico{width:36px;height:36px;border-radius:11px;background:#f6edef;color:var(--anc);display:grid;place-items:center;font-weight:900}.feed-item b{display:block;font-size:12px}.feed-item p{margin:4px 0 0;font-size:11px;color:var(--muted);line-height:1.5}.feed-item time{font-size:10px;color:#9a9ca3;white-space:nowrap}
.view{display:none}.view.active{display:block}.page-card{padding:20px}.toolbar{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:15px}.search{height:42px;min-width:250px;border:1px solid var(--line);border-radius:11px;padding:0 13px}.empty{text-align:center;color:var(--muted);padding:60px 10px}.mini-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:13px;margin-bottom:17px}.mini{padding:17px}.mini b{font-size:21px}.mini span{display:block;color:var(--muted);font-size:12px;margin-top:5px}
.modal-backdrop{position:fixed;inset:0;background:rgba(14,10,11,.55);display:grid;place-items:center;padding:18px;z-index:100}.modal-backdrop.hidden{display:none}.modal{width:min(620px,100%);background:#fff;border-radius:20px;padding:20px;box-shadow:0 24px 70px rgba(0,0,0,.28)}.modal-head{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);padding-bottom:13px}.modal-head h3{margin:0}.close{border:0;background:#f4ecee;color:var(--anc);width:36px;height:36px;border-radius:10px;cursor:pointer;font-size:20px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:17px 0}.form-grid label{font-size:12px;font-weight:700}.form-grid input,.form-grid select{width:100%;height:42px;border:1px solid var(--line);border-radius:10px;margin-top:7px;padding:0 10px}.modal-actions{display:flex;justify-content:flex-end;gap:9px}.toast{position:fixed;left:24px;bottom:24px;background:#1c2028;color:#fff;border-radius:12px;padding:12px 16px;opacity:0;transform:translateY(15px);transition:.25s;z-index:120}.toast.show{opacity:1;transform:none}
@media(max-width:1100px){.kpis{grid-template-columns:repeat(2,1fr)}.grid-2,.bottom-grid{grid-template-columns:1fr}}
@media(max-width:780px){.app{grid-template-columns:1fr}.sidebar{position:fixed;right:0;transform:translateX(105%);transition:.25s;width:280px}.sidebar.open{transform:none}.menu-btn{display:grid;place-items:center}.topbar{height:auto;min-height:82px;padding:14px 16px;align-items:flex-start;gap:12px}.top-actions{flex-wrap:wrap;justify-content:flex-end}.top-actions .select{display:none}.content{padding:16px}.hero{align-items:flex-start;gap:15px}.hero-badge{font-size:12px}.kpis{grid-template-columns:1fr 1fr}.form-grid{grid-template-columns:1fr}.mini-stats{grid-template-columns:1fr}.title h1{font-size:20px}}
@media(max-width:500px){.kpis{grid-template-columns:1fr}.hero{display:block}.hero-badge{display:inline-block;margin-top:14px}.btn-primary{padding:0 10px}.top-actions{gap:6px}.content{padding:12px}.panel{padding:15px}}
</style>
</head>
<body>
<div class="app">
  <aside class="sidebar" id="sidebar">
    <div class="brand"><img src="./assets/anc-logo.png" alt="ANC"><div class="brand-copy"><strong>Sales100</strong><span>ANC Logistics Solutions</span></div></div>
    <nav class="nav" id="nav">
      <button class="active" data-view="dashboard"><span class="ico">▦</span>لوحة التحكم</button>
      <button data-view="sales"><span class="ico">↗</span>المبيعات اليومية</button>
      <button data-view="team"><span class="ico">◎</span>فريق المبيعات</button>
      <button data-view="customers"><span class="ico">◫</span>العملاء</button>
      <button data-view="pipeline"><span class="ico">◇</span>مسار الفرص</button>
      <button data-view="reports"><span class="ico">▤</span>التقارير</button>
    </nav>
    <div class="sidebar-foot"><span class="online"></span>النظام متصل — آخر تحديث الآن</div>
  </aside>

  <main class="main">
    <header class="topbar">
      <div class="title-wrap"><button class="menu-btn" id="menuBtn">☰</button><div class="title"><h1 id="pageTitle">لوحة التحكم التنفيذية</h1><p id="pageSub">قراءة شاملة لأداء المبيعات في ANC</p></div></div>
      <div class="top-actions"><select class="select" id="month"><option>يوليو 2026</option><option>يونيو 2026</option></select><select class="select"><option>جميع المندوبين</option><option>أحمد خالد</option><option>سارة محمد</option></select><button class="btn btn-primary" id="addBtn">+ فرصة جديدة</button></div>
    </header>

    <section class="content">
      <div class="view active" id="dashboard">
        <section class="hero"><div><h2>مرحبًا بك في Sales100</h2><p>لوحة موحدة لمتابعة المستهدف، الإيراد، العملاء والفرص البيعية.</p></div><div class="hero-badge">نسبة الإنجاز <b>82%</b></div></section>
        <section class="kpis">
          <article class="card kpi"><div class="kpi-head"><span>إجمالي المبيعات</span><span class="kpi-icon">﷼</span></div><div class="kpi-value">8.24M</div><div class="trend up">▲ 12.4% مقارنة بالشهر السابق</div></article>
          <article class="card kpi"><div class="kpi-head"><span>المستهدف الشهري</span><span class="kpi-icon">◎</span></div><div class="kpi-value">10.0M</div><div class="trend">المتبقي 1.76 مليون ريال</div></article>
          <article class="card kpi"><div class="kpi-head"><span>الفرص المفتوحة</span><span class="kpi-icon">◇</span></div><div class="kpi-value">46</div><div class="trend up">بقيمة متوقعة 3.1M</div></article>
          <article class="card kpi"><div class="kpi-head"><span>العملاء النشطون</span><span class="kpi-icon">▦</span></div><div class="kpi-value">87</div><div class="trend down">▼ 3 عملاء يحتاجون متابعة</div></article>
        </section>
        <section class="grid-2">
          <article class="card panel"><div class="panel-head"><div><h3>اتجاه المبيعات اليومية</h3><p>القيمة بالآلاف خلال آخر 12 يوم عمل</p></div><span class="pill">يوليو 2026</span></div><div class="chart" id="chart"></div><div class="chart-labels" id="labels"></div></article>
          <article class="card panel"><div class="panel-head"><div><h3>تحقيق المستهدف</h3><p>الأداء الحالي مقابل خطة الشهر</p></div></div><div class="gauge"><div class="gauge-center"><strong>82%</strong><small>من المستهدف</small></div></div><div class="target-row"><span>المحقق <b>8.24M</b></span><span>المستهدف <b>10.0M</b></span></div></article>
        </section>
        <section class="bottom-grid">
          <article class="card panel"><div class="panel-head"><div><h3>ترتيب فريق المبيعات</h3><p>أعلى المندوبين تحقيقًا للمستهدف</p></div><span class="pill">10 مندوبين</span></div><div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>المندوب</th><th>المبيعات</th><th>التحقيق</th><th>الحالة</th></tr></thead><tbody id="ranking"></tbody></table></div></article>
          <article class="card panel"><div class="panel-head"><div><h3>آخر النشاطات</h3><p>التحديثات الأحدث في النظام</p></div></div><div class="feed"><div class="feed-item"><span class="feed-ico">✓</span><div><b>تم إغلاق فرصة جديدة</b><p>شركة المدى — بقيمة 245,000 ريال</p></div><time>قبل 8 د</time></div><div class="feed-item"><span class="feed-ico">+</span><div><b>تمت إضافة عميل</b><p>مجموعة أركان للخدمات اللوجستية</p></div><time>قبل 27 د</time></div><div class="feed-item"><span class="feed-ico">!</span><div><b>تنبيه متابعة</b><p>3 عروض أسعار تجاوزت 7 أيام</p></div><time>اليوم</time></div><div class="feed-item"><span class="feed-ico">↗</span><div><b>تحديث المستهدف</b><p>أحمد خالد تجاوز 100% من خطته</p></div><time>أمس</time></div></div></article>
        </section>
      </div>

      <div class="view" id="sales"><div class="mini-stats"><div class="card mini"><b>318K</b><span>مبيعات اليوم</span></div><div class="card mini"><b>24</b><span>الرحلات المباعة</span></div><div class="card mini"><b>13.2K</b><span>متوسط قيمة العملية</span></div></div><div class="card page-card"><div class="panel-head"><div><h3>سجل المبيعات اليومية</h3><p>آخر العمليات المسجلة</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>رقم العملية</th><th>العميل</th><th>المندوب</th><th>القيمة</th><th>الحالة</th></tr></thead><tbody><tr><td>#S-1049</td><td>شركة المدى</td><td>أحمد خالد</td><td>245,000 ر.س</td><td><span class="status good">مكتملة</span></td></tr><tr><td>#S-1048</td><td>مجموعة النور</td><td>سارة محمد</td><td>118,500 ر.س</td><td><span class="status good">مكتملة</span></td></tr><tr><td>#S-1047</td><td>أفق التجارة</td><td>خالد علي</td><td>76,000 ر.س</td><td><span class="status warn">مراجعة</span></td></tr></tbody></table></div></div></div>
      <div class="view" id="team"><div class="card page-card"><div class="panel-head"><div><h3>فريق المبيعات</h3><p>أداء 10 مندوبي مبيعات</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>المندوب</th><th>المنطقة</th><th>المستهدف</th><th>المحقق</th><th>النسبة</th></tr></thead><tbody id="teamRows"></tbody></table></div></div></div>
      <div class="view" id="customers"><div class="card page-card"><div class="toolbar"><div><h3 style="margin:0">العملاء</h3><p style="margin:5px 0 0;color:var(--muted);font-size:12px">قاعدة بيانات 100 عميل</p></div><input class="search" id="customerSearch" placeholder="بحث باسم العميل..."></div><div class="table-wrap"><table class="table"><thead><tr><th>العميل</th><th>القطاع</th><th>المدينة</th><th>إجمالي المبيعات</th><th>الحالة</th></tr></thead><tbody id="customerRows"></tbody></table></div></div></div>
      <div class="view" id="pipeline"><div class="mini-stats"><div class="card mini"><b>3.10M</b><span>قيمة المسار</span></div><div class="card mini"><b>46</b><span>فرصة مفتوحة</span></div><div class="card mini"><b>58%</b><span>متوسط الاحتمالية</span></div></div><div class="card page-card"><div class="panel-head"><div><h3>مسار الفرص البيعية</h3><p>توزيع الفرص حسب المرحلة</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>المرحلة</th><th>عدد الفرص</th><th>القيمة</th><th>نسبة التحويل</th></tr></thead><tbody><tr><td>Lead</td><td>18</td><td>980,000 ر.س</td><td>26%</td></tr><tr><td>Qualified</td><td>12</td><td>770,000 ر.س</td><td>42%</td></tr><tr><td>Proposal</td><td>9</td><td>810,000 ر.س</td><td>61%</td></tr><tr><td>Negotiation</td><td>7</td><td>540,000 ر.س</td><td>78%</td></tr></tbody></table></div></div></div>
      <div class="view" id="reports"><div class="card page-card"><div class="panel-head"><div><h3>التقارير</h3><p>تقارير جاهزة للطباعة والمتابعة</p></div><button class="btn" onclick="window.print()">طباعة التقرير</button></div><div class="mini-stats"><div class="card mini"><b>82%</b><span>تحقيق الشهر</span></div><div class="card mini"><b>24.7%</b><span>هامش الربح</span></div><div class="card mini"><b>11.3%</b><span>نمو الإيراد</span></div></div><p class="empty">اختر الفترة والمندوب من أعلى الصفحة ثم اطبع التقرير.</p></div></div>
    </section>
  </main>
</div>

<div class="modal-backdrop hidden" id="modal"><form class="modal" id="form"><div class="modal-head"><h3>إضافة فرصة بيعية جديدة</h3><button type="button" class="close" id="close">×</button></div><div class="form-grid"><label>اسم العميل<input required name="client" placeholder="مثال: شركة الأفق"></label><label>المندوب<select required><option>أحمد خالد</option><option>سارة محمد</option><option>خالد علي</option></select></label><label>قيمة الفرصة<input required type="number" min="1" value="50000"></label><label>المرحلة<select><option>Lead</option><option>Qualified</option><option>Proposal</option><option>Negotiation</option></select></label></div><div class="modal-actions"><button type="button" class="btn" id="cancel">إلغاء</button><button class="btn btn-primary">حفظ الفرصة</button></div></form></div>
<div class="toast" id="toast">تم حفظ الفرصة بنجاح</div>
<script>
const names=['أحمد خالد','سارة محمد','خالد علي','ريم عبدالله','محمد صالح'];
const sales=[1120000,980000,870000,760000,690000], targets=[1000000,1100000,950000,900000,850000];
const rank=document.getElementById('ranking'), team=document.getElementById('teamRows');
names.forEach((n,i)=>{const pct=Math.round(sales[i]/targets[i]*100);const cls=pct>=100?'good':pct>=80?'warn':'bad';const label=pct>=100?'متجاوز':pct>=80?'قريب':'يحتاج دعم';rank.insertAdjacentHTML('beforeend',`<tr><td><span class="rank">${i+1}</span></td><td><div class="person"><span class="avatar">${n.split(' ').map(x=>x[0]).join('')}</span><b>${n}</b></div></td><td>${sales[i].toLocaleString('en-US')} ر.س</td><td><div class="progress"><i style="width:${Math.min(pct,100)}%"></i></div><small>${pct}%</small></td><td><span class="status ${cls}">${label}</span></td></tr>`);team.insertAdjacentHTML('beforeend',`<tr><td><div class="person"><span class="avatar">${n.split(' ').map(x=>x[0]).join('')}</span><b>${n}</b></div></td><td>${['جدة','الرياض','الدمام','مكة','المدينة'][i]}</td><td>${targets[i].toLocaleString('en-US')} ر.س</td><td>${sales[i].toLocaleString('en-US')} ر.س</td><td>${pct}%</td></tr>`)});
const vals=[420,560,510,680,740,630,810,760,890,845,930,1010], labels=['1','2','3','6','7','8','9','12','13','14','15','16'];
const chart=document.getElementById('chart'), lab=document.getElementById('labels');vals.forEach((v,i)=>{chart.insertAdjacentHTML('beforeend',`<div class="bar-wrap"><div class="bar" style="height:${v/11}%"><span>${v}</span></div></div>`);lab.insertAdjacentHTML('beforeend',`<span>${labels[i]}</span>`)});
const clients=[['شركة المدى','تجارة','جدة','1,240,000'],['مجموعة النور','صناعة','الرياض','980,000'],['أفق التجارة','تجزئة','الدمام','755,000'],['أركان الخدمات','لوجستيات','جدة','630,000'],['نخبة الأغذية','أغذية','مكة','590,000'],['الرواد الطبية','طبي','الرياض','515,000'],['حلول البناء','مقاولات','المدينة','472,000'],['الصفوة القابضة','استثمار','جدة','441,000']];
const cr=document.getElementById('customerRows');function renderClients(q=''){cr.innerHTML='';clients.filter(c=>c[0].includes(q)).forEach(c=>cr.insertAdjacentHTML('beforeend',`<tr><td><b>${c[0]}</b></td><td>${c[1]}</td><td>${c[2]}</td><td>${c[3]} ر.س</td><td><span class="status good">نشط</span></td></tr>`))}renderClients();document.getElementById('customerSearch').addEventListener('input',e=>renderClients(e.target.value.trim()));
const titles={dashboard:['لوحة التحكم التنفيذية','قراءة شاملة لأداء المبيعات في ANC'],sales:['المبيعات اليومية','متابعة المبيعات والعمليات المسجلة'],team:['فريق المبيعات','تحليل أداء المندوبين والمستهدفات'],customers:['العملاء','إدارة قاعدة بيانات العملاء'],pipeline:['مسار الفرص','متابعة تقدم الفرص البيعية'],reports:['التقارير','ملخصات الإدارة ونتائج الأداء']};
document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(b.dataset.view).classList.add('active');document.getElementById('pageTitle').textContent=titles[b.dataset.view][0];document.getElementById('pageSub').textContent=titles[b.dataset.view][1];document.getElementById('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}));
document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
const modal=document.getElementById('modal');document.getElementById('addBtn').onclick=()=>modal.classList.remove('hidden');['close','cancel'].forEach(id=>document.getElementById(id).onclick=()=>modal.classList.add('hidden'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.add('hidden')});document.getElementById('form').addEventListener('submit',e=>{e.preventDefault();modal.classList.add('hidden');const t=document.getElementById('toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400);e.target.reset()});
</script>
</body>
</html>
